"""initial migration

Revision ID: 850b2342b0d3
Revises: 
Create Date: 2026-05-05 20:11:43.795366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850b2342b0d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestbook_entry',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('piece',
    sa.Column('piece_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('piece_description', sa.String(), nullable=True),
    sa.Column('order_year', sa.Integer(), nullable=True),
    sa.Column('delivery_year', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('piece_id')
    )
    op.create_table('price__sticker',
    sa.Column('price_sticker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('next_avail_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('price_sticker_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.piece_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('price__sticker')
    op.drop_table('piece')
    op.drop_table('guestbook_entry')
    # ### end Alembic commands ###
