"""rename price sticker table

Revision ID: 8e7ca2ff7f21
Revises: 850b2342b0d3
Create Date: 2026-05-05 20:19:39.437402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7ca2ff7f21'
down_revision = '850b2342b0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_sticker',
    sa.Column('price_sticker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('next_avail_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('price_sticker_id')
    )
    op.drop_table('price__sticker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price__sticker',
    sa.Column('price_sticker_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('next_avail_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('price_sticker_id', name=op.f('price__sticker_pkey'))
    )
    op.drop_table('price_sticker')
    # ### end Alembic commands ###
